version: 2
updates:
  # Root pom.xml
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sf666"
  
  # nextcp2-player
  - package-ecosystem: "maven"
    directory: "/backend/nextcp2-player"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "sf666"
